name: GitHub Actions Demo

on: 
  push: 
    branches:
      - main
  pull_request:
    branches: 
      - main
    paths-ignore: 
      - '.github/**'
  schedule:
    - cron: "15 6 * * 0"
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment"
        type: environment
        required: true
      custom-name:
        description: "What is the custom name?"
        type: string
    

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "🎉 The job was triggered by event: ${{ github.event_name }}"
          echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ."

      - uses: actions/checkout@v3.3.0

      - name: List files in the repository
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree
  
  Test:
    runs-on: ubuntu-latest
    needs: Build
    environment: Test
    if: github.event_name == 'workflow_dispatch'
    steps:
      - run: |
          echo "Testing"
          sleep 3

  Load-Test:
    runs-on: ubuntu-latest
    needs: Build
    environment: Load-Test
    if: github.event_name == 'workflow_dispatch'
    steps:
      - run: |
          echo "Load Testing"
  
  Production:
    runs-on: ubuntu-latest
    needs: [Test, Load-Test]
    environment:
      name: Production
      url: https://github.com
    if: github.event_name == 'workflow_dispatch'
    steps:
      - run: |
          echo "Running step 1"
          sleep 2
      - run: |
          echo "Job is trying to configure environment
          sleep 4
      - run: |
          echo "Additional configuration applying"
          sleep 5
      - run: |
          echo "Job completed"
